#!/bin/bash
# plan-chronicle.sh — Deterministic chronicle stub at plan boundaries
#
# Creates a guaranteed chronicle entry at plan lifecycle boundaries.
# Reuses the dedup/label pattern from plan-exec.sh create_transition_chronicle().
#
# Usage:
#   plan-chronicle.sh save   <plan_label> [plan_file_path]
#   plan-chronicle.sh intake <plan_label> [plan_file_path]
#
# Fail-open: always exits 0.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/yf-tasks.sh"

COMMAND="${1:-}"
PLAN_LABEL="${2:-}"
PLAN_FILE="${3:-}"

if [[ -z "$COMMAND" || -z "$PLAN_LABEL" ]]; then
    echo "Usage: plan-chronicle.sh <save|intake> <plan_label> [plan_file_path]" >&2
    exit 0  # fail-open
fi

# --- Dedup: one chronicle per plan-boundary per day ---
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
DEDUP_DIR="${PROJECT_DIR}/.yoshiko-flow"
DEDUP_FILE="${DEDUP_DIR}/.chronicle-plan-$(date +%Y%m%d)"
DEDUP_KEY="${PLAN_LABEL}-${COMMAND}"

mkdir -p "$DEDUP_DIR" 2>/dev/null || true
if [ -f "$DEDUP_FILE" ] && grep -qF "$DEDUP_KEY" "$DEDUP_FILE" 2>/dev/null; then
    exit 0  # already created today
fi

# --- Build description from plan file context ---
PLAN_EXCERPT=""
if [[ -n "$PLAN_FILE" && -f "$PLAN_FILE" ]]; then
    PLAN_EXCERPT=$(head -20 "$PLAN_FILE" 2>/dev/null || true)
fi

case "$COMMAND" in
    save)
        TITLE="Chronicle (Auto): Plan ${PLAN_LABEL} — save"
        DESCRIPTION="## Plan Save Chronicle

**Plan**: ${PLAN_LABEL}
**Boundary**: plan-save (ExitPlanMode)
**Date**: $(date '+%Y-%m-%d %H:%M')

## Plan Excerpt
${PLAN_EXCERPT:-No plan file provided.}

Auto-generated by plan-chronicle.sh at plan-save boundary."
        ;;
    intake)
        TITLE="Chronicle (Auto): Plan ${PLAN_LABEL} — intake"
        DESCRIPTION="## Plan Intake Chronicle

**Plan**: ${PLAN_LABEL}
**Boundary**: plan-intake (manual/pasted plan)
**Date**: $(date '+%Y-%m-%d %H:%M')

## Plan Excerpt
${PLAN_EXCERPT:-No plan file provided.}

Auto-generated by plan-chronicle.sh at plan-intake boundary."
        ;;
    *)
        echo "Unknown command: $COMMAND (expected save or intake)" >&2
        exit 0  # fail-open
        ;;
esac

LABELS="ys:chronicle,ys:chronicle:auto,ys:topic:planning"
if [[ -n "$PLAN_LABEL" ]]; then
    LABELS="${LABELS},${PLAN_LABEL}"
fi

yft_create --type=chronicle --priority=3 \
    -l "$LABELS" \
    --title "$TITLE" \
    --description "$DESCRIPTION" >/dev/null 2>&1 || exit 0

echo "$DEDUP_KEY" >> "$DEDUP_FILE" 2>/dev/null || true
echo "Chronicle stub created: ${TITLE}"
